"use strict";

const CONSTANTS = {
    CONSUMER_KEY: "B2BLUESRJVOC06IX9PYNZTNVV1HYUD",
    CONSUMER_SECRET: "BJHCSQTVQRLTV99W0420NQYLOQ9UET",
    API_VERSION: "2.0",
    CALLBACK_URL: "example.com"
};

module.exports = CONSTANTS;
